### ISSUE TITLE
loop_infinite could be dynamic

### ISSUE THREAD

**Issue by spacemeowx2** [szymonwieloch/rust-rawsock#4]
https://github.com/spacemeowx2/rust-rawsock/commit/b64f79b0de9b3fce8ef2618a9b56a5b4d3f1d6de

btw I also want trait `Interface` and `Library` impls `Send` and `Sync` for multi-thread. Because I need to break loop from other thread.

**Comment by szymonwieloch** [comment]
@spacemeowx2 loop_infinite() was supposed to be in two versions, I simply didn't have time to implement it. It is done now. Please notice that this is an experimental version and I didn't have enough time to test it. I will add more tests over the weekend. I hope it is going to be OK.

**Comment by szymonwieloch** [comment]
@spacemeowx2 BTW, I have also added Sync and Send
